/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppDisponibilidadeRouteImport } from './routes/app.disponibilidade'
import { Route as AppEscalasRouteImport } from './routes/app.escalas'
import { Route as AppEventosRouteImport } from './routes/app.eventos'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppMinisteriosRouteImport } from './routes/app.ministerios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppServosRouteImport } from './routes/app.servos'
import { Route as AppServosIdRouteImport } from './routes/app.servos_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDisponibilidadeRoute = AppDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasRoute = AppEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppMinisteriosRoute = AppMinisteriosRouteImport.update({
  id: '/ministerios',
  path: '/ministerios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppServosRoute = AppServosRouteImport.update({
  id: '/servos',
  path: '/servos',
  getParentRoute: () => AppRoute,
} as any)
const AppServosIdRoute = AppServosIdRouteImport.update({
  id: '/servos_/$id',
  path: '/servos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/disponibilidade': typeof AppDisponibilidadeRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/ministerios': typeof AppMinisteriosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servos': typeof AppServosRoute
  '/app/': typeof AppIndexRoute
  '/app/servos/$id': typeof AppServosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/disponibilidade': typeof AppDisponibilidadeRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/ministerios': typeof AppMinisteriosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servos': typeof AppServosRoute
  '/app': typeof AppIndexRoute
  '/app/servos/$id': typeof AppServosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/disponibilidade': typeof AppDisponibilidadeRoute
  '/app/escalas': typeof AppEscalasRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/ministerios': typeof AppMinisteriosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/servos': typeof AppServosRoute
  '/app/': typeof AppIndexRoute
  '/app/servos_/$id': typeof AppServosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/admin'
    | '/app/disponibilidade'
    | '/app/escalas'
    | '/app/eventos'
    | '/app/inicio'
    | '/app/ministerios'
    | '/app/perfil'
    | '/app/servos'
    | '/app/'
    | '/app/servos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/admin'
    | '/app/disponibilidade'
    | '/app/escalas'
    | '/app/eventos'
    | '/app/inicio'
    | '/app/ministerios'
    | '/app/perfil'
    | '/app/servos'
    | '/app'
    | '/app/servos/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/app/admin'
    | '/app/disponibilidade'
    | '/app/escalas'
    | '/app/eventos'
    | '/app/inicio'
    | '/app/ministerios'
    | '/app/perfil'
    | '/app/servos'
    | '/app/'
    | '/app/servos_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disponibilidade': {
      id: '/app/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/app/disponibilidade'
      preLoaderRoute: typeof AppDisponibilidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escalas': {
      id: '/app/escalas'
      path: '/escalas'
      fullPath: '/app/escalas'
      preLoaderRoute: typeof AppEscalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eventos': {
      id: '/app/eventos'
      path: '/eventos'
      fullPath: '/app/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ministerios': {
      id: '/app/ministerios'
      path: '/ministerios'
      fullPath: '/app/ministerios'
      preLoaderRoute: typeof AppMinisteriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servos': {
      id: '/app/servos'
      path: '/servos'
      fullPath: '/app/servos'
      preLoaderRoute: typeof AppServosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servos_/$id': {
      id: '/app/servos_/$id'
      path: '/servos/$id'
      fullPath: '/app/servos/$id'
      preLoaderRoute: typeof AppServosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDisponibilidadeRoute: typeof AppDisponibilidadeRoute
  AppEscalasRoute: typeof AppEscalasRoute
  AppEventosRoute: typeof AppEventosRoute
  AppInicioRoute: typeof AppInicioRoute
  AppMinisteriosRoute: typeof AppMinisteriosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppServosRoute: typeof AppServosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppServosIdRoute: typeof AppServosIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDisponibilidadeRoute: AppDisponibilidadeRoute,
  AppEscalasRoute: AppEscalasRoute,
  AppEventosRoute: AppEventosRoute,
  AppInicioRoute: AppInicioRoute,
  AppMinisteriosRoute: AppMinisteriosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppServosRoute: AppServosRoute,
  AppIndexRoute: AppIndexRoute,
  AppServosIdRoute: AppServosIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
